#!/bin/bash

# Run: git config core.hooksPath `pwd`/.githooks
set -e

if [[ $(redis-cli EXISTS calc_already_updated) != "1" ]]; then
    make update
    redis-cli SET calc_already_updated 1 EX 86400 > /dev/null
fi

make release
