#!/bin/bash

# Run: git config core.hooksPath `pwd`/.githooks

# Update deps if it's Monday
if [[ `date '+%A'` == "Monday" ]]; then
cargo update
EXIT_CODES+=( $? )
fi

make release
EXIT_CODES+=( $? )

git add Cargo.lock docs
EXIT_CODES+=( $? )

# Check that all commands exited with success (0), and if not, stop the commit
for e in ${EXIT_CODES[@]}; do
   if [[ $e -gt 0 ]]
   then
       exit 1
   fi
done
