[package]
name = "calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.31.*"
egui = "0.31.*"
chrono = "0.4.*"
pest = "2.7.*"
pest_derive = "2.7.*"
