[package]
name = "calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "~0.27.2"
chrono = "~0.4.23"
pest = "~2.7.11"
pest_derive = "~2.5.5"
