[package]
name = "interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain"}
eframe = "0.20.1"
egui = "0.20.1"
egui_vulkano = "0.8.0"
vulkano = "0.32.3"
