name: Calc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Install OS level dependancies
      run: sudo apt install libgtk-4-dev build-essential -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
